### ISSUE TITLE
Error: Getting key-file failed

### ISSUE THREAD

**Issue by truedread** [selsta/hlsdl#11]
Getting this (Error: Getting key-file failed) error when trying to download streams from this m3u8 url: http://hlsvod-l3c.med3.hbonow.com/hls/2017/01/26/74/741104f3-1693-444d-83e2-5bb4d0760119/1485403291688/s1/master_wired_web_s1_primetime.m3u8

It does download all parts of the .ts streams, but the keys are 0 and it isn't fully decrypted.

**Comment by selsta** [comment]
hlsdl can’t download DRM protected streams.
