### ISSUE TITLE
sample rate not set

### ISSUE THREAD

**Issue by wernerkarlheisenberg** [selsta/hlsdl#12]
When trying to convert a M3U8 file that is SAMPLE-AES encrypted I get the following error.

HLS Stream is SAMPLE-AES encrypted.
Media Playlist parsed successfully.
Downloading 325 segments.
Downloading part 0
[mpegts @ 0x7fb4ef01d000] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[mpegts @ 0x7fb4ef01d000] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x7fb4ef01d000] sample rate not set
Error: Writing header failed.
Segmentation fault: 11

**Comment by wernerkarlheisenberg** [comment]
Sorry for the confusion, I tried to remove the sample URL that I provided. Problem still exists.

**Comment by selsta** [comment]
Okay, looks like your original sample used DRM, which is not supported.

**Comment by selsta** [comment]
But i guess there is still some deprecated ffmpeg api usage in my project

**Comment by Mike-Skinner** [comment]
Hi Selsta,

I get the same:

```
./hlsdl "https://server/path.m3u8" --verbose
Debug: Loglevel: 2
HLS Stream is SAMPLE-AES encrypted.
Media Playlist parsed successfully.
Downloading 1470 segments.
Downloading part 0
[mpegts @ 0x56016d39bc40] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[mpegts @ 0x56016d39bc40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x56016d39bc40] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mpegts @ 0x56016d39bc40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Downloading part 1
[mpegts @ 0x56016be75fa0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[mpegts @ 0x56016be75fa0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpegts @ 0x56016be75fa0] sample rate not set
Error: Writing header failed.
Segmentation fault (core dumped)
```

This is on Ubuntu 17.04.

How would I know whether there is DRM in my file? Hopefully the stream isn't DRMed as well being SAMPLE-AES encrypted.

Is there anyway I could manually code in a timebase setting, or pass in a command line argument to set one manually?

Do you think the DRM key is constant for the whole stream or does it change periodically during playback?

Kind Regards,

Mike

**Comment by selsta** [comment]
If Safari / QuickTime can play the HLS link it does not use DRM

**Comment by wernerkarlheisenberg** [comment]
Sorry for the late reply, in my case there is no DRM.

**Comment by selsta** [comment]
I’m not sure if this is still relevant but I’ve found a stream to debug this. I’ll try my best to fix this bug.

**Comment by Mike-Skinner** [comment]
Hi Selsta,

I don't have OS X / Safari (to test my stream for DRM), but I'm happy to test once you're done.

Good luck!

**Comment by wernerkarlheisenberg** [comment]
In found another solution in the mean time. But if you want me to test, I'm happy together do so.

**Comment by selsta** [comment]
Should be fixed.
