### ISSUE TITLE
Timeout was reached. 

### ISSUE THREAD

**Issue by haleyngonadi** [selsta/hlsdl#13]
Hi. I'm not sure you still run ths but I thought it would be worth a shot. I'm trying to download a basic strem but I keep getting:

```
Downloading part 0
Error: curl_easy_perform() failed: Timeout was reached
Warning: VOD retry segment 0 download, due to previous error. http_code[0].

```

The URL is: http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

**Comment by selsta** [comment]
Hi!
Just tried out your stream and it worked fine for me.
Seems like a network error on your side maybe?

**Comment by haleyngonadi** [comment]
Oh my gosh, you already replied! Thank you so much. I just tried another stream and this time, it says no_ffmpeg even though I have it installed. Any idea why?

**Comment by selsta** [comment]
Could you paste the whole terminal ouput? :)

**Comment by haleyngonadi** [comment]
Downloading part 199
{"error_code":-12, "error_msg":"no_ffmpeg"}
{"t_d":3086,"d_d":800,"d_s":308594668}
Downloading part 200

The video is downloading nonetheless but looks like this: 

![untitled](https://cloud.githubusercontent.com/assets/6877114/26167185/194b8cb4-3b04-11e7-89cc-65c912c86807.png)

**Comment by haleyngonadi** [comment]
UPDATE: I tried downloading it from a different computer and now it says 

```
Choosing best quality. (Bitrate: 6256000)
Segmentation fault: 11
```

If you could give me your email, I'd send over the URL x)

**Comment by selsta** [comment]
Hi

I'll look at it when I'm home, but it looks like you did something wrong while compiling the program.

You can send the sample URL to selsta at sent.at
