### ISSUE TITLE
install problems on centos 6.9

### ISSUE THREAD

**Issue by chipzidar** [selsta/hlsdl#15]
`# make && make install && make clean
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -g -DPREFIX='"/usr/local"' -D_GNU_SOURCE=1 -std=gnu99 -c src/main.c -o src/main.o
src/main.c:1:34: error: libavformat/avformat.h: No such file or directory
src/main.c: In function ‘main’:
src/main.c:25: warning: implicit declaration of function ‘av_register_all’
make: *** [src/main.o] Error 1
`

**Comment by selsta** [comment]
Did you install FFmpeg?

`yum -y install ffmpeg ffmpeg-devel`

**Comment by chipzidar** [comment]
yes ffmpeg is installed 
`# ffmpeg
ffmpeg version N-82999-g72d6101 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-17)
  configuration: --prefix=/ffmpeg_build --extra-cflags=-I/ffmpeg_build/include -                                                                                        -extra-ldflags=-L/ffmpeg_build/lib --bindir=/usr/bin --pkg-config-flags=--static                                                                                         --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable                                                                                        -libmp3lame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.101 / 57. 70.101
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfi                                                                                        le}...

Use -h to get full help or, even better, run 'man ffmpeg'
`

**Comment by selsta** [comment]
But did you also install `ffmpeg-devel`?
As far as I can tell from your error log it can't find the libav* header files.

**Comment by chipzidar** [comment]
not available 
``
No package ffmpeg-devel available.
Error: Nothing to do
#
``

**Comment by selsta** [comment]
Does this help? https://linoxide.com/linux-how-to/install-ffmpeg-centos-7/
