### ISSUE TITLE
i got error in the compile 

### ISSUE THREAD

**Issue by kaka052003** [selsta/hlsdl#18]
:~/hlsdl# make
cc src/main.o src/aes.o src/curl.o src/hls.o src/misc.o src/msg.o -lcurl -lavformat -lavutil -lavcodec -o hlsdl
src/hls.o: In function `decrypt_sample_aes':
/root/hlsdl/src/hls.c:478: undefined reference to `av_packet_unref'
collect2: error: ld returned 1 exit status

this is error , i need help please

**Comment by selsta** [comment]
Update your ffmpeg
