### ISSUE TITLE
QUESTION: "Warning: Not a valid M3U8 file. Exiting."

### ISSUE THREAD

**Issue by doio** [selsta/hlsdl#19]
I wanted to download this m3u8 file:
[Original m3u8](https://cp477480-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgBnUgX1pf6SNvJWsllIjyNsap6WFyeY9tq0FFy2r+8QRiojDFaT//TH4ZjQwnMo74KRMSiD/HSztA==&hdntl=exp=1504946290~acl=/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/*~data=hdntl~hmac=5ad40583c63d068f1913c9748b665235ea7a33496371ff8cfa412942a9963c06)

[Hosted File](https://dl7.volafile.org/get/gIMEpESmkM3W/index_6_av.m3u8)

I never seem to get past the warning, can you have a look? 
Thank you.

**Comment by selsta** [comment]
I think you have to pass cookies to download this file which I have not implemented.

ffmpeg does support this. (https://ffmpeg.org/ffmpeg-protocols.html#HTTP-Cookies)

**Comment by doio** [comment]
Hello, I appreciate your prompt reply.
Could this be you have to access the file from a US-based IP?

Anyway would you be implementing the support in the near future?

Thanks again.

**Comment by selsta** [comment]
Could you paste me the output of

```curl "https://cp477480-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgBnUgX1pf6SNvJWsllIjyNsap6WFyeY9tq0FFy2r+8QRiojDFaT//TH4ZjQwnMo74KRMSiD/HSztA==&hdntl=exp=1504946290%7Eacl=/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/*%7Edata=hdntl%7Ehmac=5ad40583c63d068f1913c9748b665235ea7a33496371ff8cfa412942a9963c06"```

**Comment by doio** [comment]
Using Firefox the link appears valid. But pasting the command in Terminal gets me 

`<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;cp477480&#45;vh&#46;akamaihd&#46;net&#47;i&#47;mtvnorigin&#47;gsp&#46;alias&#47;mediabus&#47;logo&#46;com&#47;2016&#47;09&#47;08&#47;01&#47;53&#47;31&#47;c2617bae28b84e0fbfd8efa564833dbb&#47;1299295&#47;ywKgKfbDaj&#95;6671093&#95;1299295&#95;20160908135331108&#95;&#44;384x216&#95;278&#44;512x288&#95;498&#44;640x360&#95;1028&#44;768x432&#95;1528&#44;960x540&#95;2128&#44;1280x720&#95;3128&#44;1920x1080&#95;5128&#44;&#46;mp4&#46;csmil&#47;index&#95;6&#95;av&#46;m3u8&#63;" on this server.<P>
Reference&#32;&#35;18&#46;3692fea5&#46;1504869189&#46;4204949
</BODY>
</HTML>
`

**Comment by selsta** [comment]
Yup, it’s cookie and not IP related. You have to find the cookie in your Browser. Can you try to open the .m3u8 in Firefox and then open the Firefox Developer Tools -> Storage Inspector -> Cookies and look if something is there?

**Comment by doio** [comment]
Maybe you could try the URL in this JSON file?
https://media-utils.mtvnservices.com/services/MediaGenerator/mgid:arc:video:logotv.com:2a3de6de-2d19-408d-9de3-0f453ec69e5a?arcStage=live&isEpisode=true&format=json&acceptMethods=hls

> Found 7 Qualitys
> 
> 0: Bandwidth: 278000
> 1: Bandwidth: 488000
> 2: Bandwidth: 871000
> 3: Bandwidth: 1141000
> 4: Bandwidth: 1770000
> 5: Bandwidth: 2748000
> 6: Bandwidth: 4744000
> Which Quality should be downloaded?

I entered 6 but it returned: -bash: 6: command not found

[2]+  Stopped                 hlsdl https://cp477480-vh.akamaihd.net/...a44652c6

**Comment by selsta** [comment]
The URL in the JSON file works for me. I can download it with the best quality.

```
Found 7 Qualitys

0: Bandwidth: 488000
1: Bandwidth: 278000
2: Bandwidth: 871000
3: Bandwidth: 1141000
4: Bandwidth: 1770000
5: Bandwidth: 2748000
6: Bandwidth: 4744000
Which Quality should be downloaded? 6
HLS Stream is AES-128 encrypted.
Media Playlist parsed successfully.
Downloading 108 segments.
Downloading part 0
Downloading part 1
Downloading part 2
^C⏎  
```

The 6 error is weird. Can you paste me your full CLI input and output?

**Comment by doio** [comment]
Milos-MacBook-Pro:~ o_o$ hlsdl https://cp477480-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/master.m3u8?hdnea=st%3D1504869340%7Eexp%3D1504883740%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.alias%2Fmediabus%2Flogo.com%2F2016%2F09%2F08%2F01%2F53%2F31%2Fc2617bae28b84e0fbfd8efa564833dbb%2F1299295%2FywKgKfbDaj_6671093_1299295_20160908135331108_%2C384x216_278%2C512x288_498%2C640x360_1028%2C768x432_1528%2C960x540_2128%2C1280x720_3128%2C1920x1080_5128%2C.mp4.csmil%2F*%7Ehmac%3D740ad3f43e3c627c20745373eacf58c437c64ab42bd3f05ce4689b1ba44652c6&__a__=off&__b__=450&__viacc__=NONE
[2] 41644
[3] 41645
[4] 41646
[3]   Done                    __a__=off
[4]-  Done                    __b__=450
Milos-MacBook-Pro:~ o_o$ Found 7 Qualitys

0: Bandwidth: 278000
1: Bandwidth: 488000
2: Bandwidth: 871000
3: Bandwidth: 1141000
4: Bandwidth: 1770000
5: Bandwidth: 2748000
6: Bandwidth: 4744000
Which Quality should be downloaded? 6
-bash: 6: command not found

[2]+  Stopped                 hlsdl https://cp477480-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/logo.com/2016/09/08/01/53/31/c2617bae28b84e0fbfd8efa564833dbb/1299295/ywKgKfbDaj_6671093_1299295_20160908135331108_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/master.m3u8?hdnea=st%3D1504869340%7Eexp%3D1504883740%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.alias%2Fmediabus%2Flogo.com%2F2016%2F09%2F08%2F01%2F53%2F31%2Fc2617bae28b84e0fbfd8efa564833dbb%2F1299295%2FywKgKfbDaj_6671093_1299295_20160908135331108_%2C384x216_278%2C512x288_498%2C640x360_1028%2C768x432_1528%2C960x540_2128%2C1280x720_3128%2C1920x1080_5128%2C.mp4.csmil%2F*%7Ehmac%3D740ad3f43e3c627c20745373eacf58c437c64ab42bd3f05ce4689b1ba44652c6
Milos-MacBook-Pro:~ o_o$ 


PS.: Yep there's something in Cookies panel about https://media-utils.mtvnservices.com/
Surprisingly this URL alone, https://media-utils.mtvnservices.com/services/MediaGenerator/mgid:arc:video:logotv.com:2a3de6de-2d19-408d-9de3-0f453ec69e5a

Shows all the available quality and but in RTMPE:// protocol.

**Comment by selsta** [comment]
You are missing URL escaping. Put the URL in quotes, it will work :)

**Comment by doio** [comment]
arghh, sorry I missed it. 

It works now, thank you very much! 👍
