### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by davidlucid** [selsta/hlsdl#2]
~/hlsdl$ sudo make && make install && make clean

cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -g -DPREFIX='"/usr/local"' -D_GNU_SOURCE=1 -std=gnu99 -c src/hls.c -o src/hls.o
src/hls.c: In function ‘decrypt_sample_aes’:
src/hls.c:334:38: error: ‘AV_CODEC_ID_H264’ undeclared (first use in this function)
src/hls.c:334:38: note: each undeclared identifier is reported only once for each function it appears in
src/hls.c:374:18: error: variable ‘cid’ has initializer but incomplete type
src/hls.c:374:28: error: storage size of ‘cid’ isn’t known
src/hls.c:375:24: error: ‘AV_CODEC_ID_AAC’ undeclared (first use in this function)
src/hls.c:381:31: error: ‘AV_CODEC_ID_AC3’ undeclared (first use in this function)
src/hls.c:374:28: warning: unused variable ‘cid’ [-Wunused-variable]
make: *** [src/hls.o] Error 1

Why does this happen?

**Comment by selsta** [comment]
What’s your OS? You have to install the libav* librarys. They come with ffmpeg.

**Comment by davidlucid** [comment]
I'm using Ubuntu, and I ran `sudo apt-get install ffmpeg` and `sudo apt-get install libavformat53 libavformat-dev libavcodec53`. Doing so solved the other errors telling me I needed those libraries, but now this one popped up.

**Comment by davidlucid** [comment]
`~$ sudo apt-get install libavformat53 libavformat-dev libavcodec53 libavcodec-dev ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ffmpeg is already the newest version.
libavcodec-dev is already the newest version.
libavcodec53 is already the newest version.
libavformat-dev is already the newest version.
libavformat53 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 674 not upgraded.`

**Comment by davidlucid** [comment]
~$ sudo apt-get install libavformat53 libavformat-dev libavcodec53 libavcodec-dev ffmpeg

Reading package lists... Done
Building dependency tree
Reading state information... Done
ffmpeg is already the newest version.
libavcodec-dev is already the newest version.
libavcodec53 is already the newest version.
libavformat-dev is already the newest version.
libavformat53 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 674 not upgraded.

**Comment by selsta** [comment]
So what happens when you are trying to compile now?

**Comment by davidlucid** [comment]
Oh, it's still the same errors. I was just saying what I did prior to those errors. I'll start from the beginning. It started off telling me I needed to install libavformat and all that, so I did. As you can see by my previous comment, all of those libraries are installed. But now I get errors telling me about these undeclared identifiers.

**Comment by selsta** [comment]
Hmm, weird. I just tried it on an ubuntu VM and compiling works fine.
`sudo apt-get install libavformat-dev libcurl4-gnutls-dev` is what I had to install.

**Comment by davidlucid** [comment]
Finally got it to work on a new install of Ubuntu 14.04. Not sure what was happening previously, but it's all good now. Thanks for the help.
