### ISSUE TITLE
About that segfault issue from earlier...

### ISSUE THREAD

**Issue by ringofyre** [selsta/hlsdl#20]
Sorry to have to create a new issue but I wasn't sure how else to contact you. Don't need a response - close this off after you've read it by all means.
File was corrupt.
File was about 600mb so a lot of errors, I'll post the different types in what order I can get to (scrollback on bash is small) in case any of it helps.

[ffmpeg/audio] aac: Number of bands (52) exceeds limit (42).
Error decoding audio.
[ffmpeg/audio] aac: TNS filter order 16 is greater than maximum 12.
Error decoding audio.
[ffmpeg/audio] aac: TNS filter order 19 is greater than maximum 12.
Error decoding audio.
[ffmpeg/audio] aac: SSR is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[ffmpeg/audio] aac: If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)

[ffmpeg/audio] aac: Sample rate index in program config element does not match the sample rate index configured by the container.
[ffmpeg/audio] aac: decode_pce: Input buffer exhausted before END element found
Error decoding audio.

[ffmpeg/video] h264: error while decoding MB 12 0, bytestream 9100
[ffmpeg/video] h264: top block unavailable for requested intra mode -1

[ffmpeg/video] h264: top block unavailable for requested intra mode -1
[ffmpeg/video] h264: error while decoding MB 11 0, bytestream 7088
AV: 00:20:48 / 00:43:00 (60%) A-V:  0.000 Cache:  9s+73MB
[ffmpeg/video] h264: Reference 3 >= 3
[ffmpeg/video] h264: error while decoding MB 39 1, bytestream 5781

Cheers for your help, much appreciated.

**Comment by selsta** [comment]
I guess I need an Australian VPN to debug this.

**Comment by ringofyre** [comment]
I'm happy to help where I can - working on a live usb atm as my work laptop is on loan but I can clone and rebuild repeatedly if needs.
File is borked - no sound and grey screen in mplayer.

**Comment by selsta** [comment]
Don’t know how to debug this. Tried 4 different Australian IPs and they all are geo-blocked.

**Comment by selsta** [comment]
Is it possible that the stream has DRM?
