### ISSUE TITLE
Compilation problem: undefined reference to `avcodec_parameters_copy'

### ISSUE THREAD

**Issue by rprata** [selsta/hlsdl#22]
Hi, 
I tried to compile this project on Ubuntu16.04, however I had this problem:
_undefined reference to `avcodec_parameters_copy'_

So, what's the libac version and how that you compile libav (configure flags)?

Best Regards, 
Renan

**Comment by selsta** [comment]
`sudo apt-get install libavformat-dev libavcodec-dev`

Does that help?

**Comment by fstarkenberg** [comment]
I hade the same issue but got it working when using an older commit.
`git checkout a68e51d9668ff1b4cfb70af1e3ef94001bdc521b` worked for me.

**Comment by selsta** [comment]
That means you are using an old version of FFmpeg.

**Comment by fstarkenberg** [comment]
`ffmpeg version 2.8.11-0ubuntu0.16.04.1`.
That makes sense and is probably to be expected by an LTS release.

**Comment by rprata** [comment]
@selsta, you should inform the ffmpeg minimum version in your README. I updated here and works. Thank you.
