### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by hon3yl0v3r** [selsta/hlsdl#23]
Hi!
After a lot of research I found this tool. I really need it badly to decrypt sample-aes,KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"(You know what this is!). I know a little bit programming in C(compared to you, i'm just starting out). I have found your code pretty amazing. But I am not able to use this perfect tool to my liking. Can you please teach me how this works? It would be really a huge help. I really want to understand this code. Please help and don't say NO.

**Comment by selsta** [comment]
`KEYFORMAT="com.apple.streamingkeydelivery" `

DRM, hlsdl can’t download such videos.
