### ISSUE TITLE
Error: Video or Audio missing.Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SSoft7** [selsta/hlsdl#25]
Hello,

My m3u8 file(starting) looks  like this 

#EXTM3U
#EXT-X-VERSION:4
## Created with Unified Streaming Platform(version=1.7.25)
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://fairplay",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

i suppose this is DRM ,any possibility you can implement this decryption ? its really annoying . 

thanks

**Comment by selsta** [comment]
Sorry, I can’t break DRM protection.

**Comment by vsambor** [comment]
@selsta does this lib work if I use a decryption key for a DRM stream? Thanks

**Comment by xavave** [comment]
@vsambor you can pass a decryption AES Hex key with parameter -K
