### ISSUE TITLE
cant build this , how to build it ?

### ISSUE THREAD

**Issue by omgbox** [selsta/hlsdl#3]
>~/Downloads/hlsdl# make
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -g -DPREFIX='"/usr/local"' -D_GNU_SOURCE=1 -std=gnu99 -c src/hls.c -o src/hls.o
src/hls.c: In function ‘decrypt_sample_aes’:
src/hls.c:334:38: error: ‘AV_CODEC_ID_H264’ undeclared (first use in this function)
src/hls.c:334:38: note: each undeclared identifier is reported only once for each function it appears in
src/hls.c:374:18: error: variable ‘cid’ has initializer but incomplete type
src/hls.c:374:28: error: storage size of ‘cid’ isn’t known
src/hls.c:375:24: error: ‘AV_CODEC_ID_AAC’ undeclared (first use in this function)
src/hls.c:381:31: error: ‘AV_CODEC_ID_AC3’ undeclared (first use in this function)
src/hls.c:374:28: warning: unused variable ‘cid’ [-Wunused-variable]
src/hls.c:478:9: warning: implicit declaration of function ‘av_packet_unref’ [-Wimplicit-function-declaration]
make: *** [src/hls.o] Error 1

**Comment by selsta** [comment]
Hey, what is you OS?

Is seems like you don't have the ffmpeg librarys installed.

**Comment by chovy** [comment]
i couldn't build on debian using latest builds.

**Comment by selsta** [comment]
I’ve just successfully installed hlsdl on the latest Debian version.

FFmpeg: https://www.assetbank.co.uk/support/documentation/install/ffmpeg-debian-squeeze/ffmpeg-debian-jessie/
libcurl: `apt-get install libcurl4-openssl-dev`

**Comment by selsta** [comment]
Ping?
