### ISSUE TITLE
Stack smashing detected

### ISSUE THREAD

**Issue by nimloc** [selsta/hlsdl#35]
I get stack smashing detected WARNING when attempting to download certain links. I can PM you the link. Other links work well.

I am using the latest version of hlsdl, ffmpeg and ubuntu.

**Comment by selsta** [comment]
Sample links would be helpful

selsta [at] sent [.] at

**Comment by jimsy3** [comment]
how do i install this tool plz?

**Comment by nimloc** [comment]
"Sample links would be helpful"

Thanks selsta for the kind reply. Sorry for the late response from me. I found another much less elegant solution that worked for me in the end. Thank you very much for producing this valuable utility. I hope to try it again. 

jimsy3... I can't help you with how to install being new to this. Sorry. I hope you get it sorted.

**Comment by samsamsam-iptvplayer** [comment]
This problem "stack smashing detected " was found and solved on my branch:
https://github.com/samsamsam-iptvplayer/hlsdl/commit/5508fd65b651adb32ec54a8c7168220bbe1ff777

The problem was with scanf function when iv was read.
Example playlist on which problem can be reproduced:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:70694
#EXT-X-KEY:METHOD=AES-128,URI="/auth/key/bb753d1350b09aeaf6248755f54b60ccaa3d11b0/",IV=0x6363a8c96f59d307ccd476b15973ed5f,KEYFORMATVERSIONS="1"
#EXTINF:7.68,
media-u6owbxkn9_b2928000_70694.ts
#EXTINF:7.68,
media-u6owbxkn9_b2928000_70695.ts
#EXTINF:7.68,
media-u6owbxkn9_b2928000_70696.ts

```

**Comment by selsta** [comment]
@samsamsam-iptvplayer 

Does this look right? 1e5f75d

**Comment by samsamsam-iptvplayer** [comment]
Yes exactly.

**Comment by selsta** [comment]
Thanks! :)

**Comment by samsamsam-iptvplayer** [comment]
No problem. Thanks for very nice project.
