### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by d3ibis** [selsta/hlsdl#36]
Dear,

Thank you for such tool that I hoped it will solve my problem! Here is my command:

`hlsdl "***********.ism/FOR0040971_12615_(12615_ISMUSP)-audio_eng=80001-video_eng=2404000.m3u8" -b -v --dump-dec-cmd -o /Users/d3ibis/Desktop/TestTVAE.mp4`

Stars to hide url and other commands (b, v, dump..etc) for my own research...

here is the result:

`Debug: Loglevel: 2
Warning: HLS stream is DRM protected. Exiting`

Really ? this is a sample-aes playlist which is encrypted and DRM (thats why sample-aes is there)

here is then header of the m3u8 file:

`#EXTM3U
#EXT-X-VERSION:5
## Created with Unified Streaming Platform(version=1.7.19)
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:8
#USP-X-TIMESTAMP-MAP:MPEGTS=900000,LOCAL=1970-01-01T00:00:00Z
#EXTINF:8, no desc
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://****************",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"`

Any ideas ?

Thanks in advance...

**Comment by selsta** [comment]
hlsdl only supports sample-aes without DRM :/
