### ISSUE TITLE
downloaded files

### ISSUE THREAD

**Issue by chovy** [selsta/hlsdl#4]
it downloaded files....but i couldn't decrypt them.

script to run on downloaded .ts file:
```
hexKey=$(cat espn2.key | hexdump -e '16/1 "%02x"')
hexIV='0000000000000000000000000000CA80'

openssl aes-128-cbc -d -p -nosalt -iv ${hexIV} -K ${hexKey} -in encrypted.ts -out decrypted.ts
```

error
```
bad decrypt
9030:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad 
decrypt:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59/src/crypto/evp/evp_enc.c:330:
```

**Comment by selsta** [comment]
hlsdl decrypts the files automatically, you don’t have to run a script.

A link to reproduce would be helpful.

**Comment by chovy** [comment]
I couldn't play the .ts files so something went wrong with decrypting.

**Comment by selsta** [comment]
I can’t help you without a link to reproduce your issue.

**Comment by selsta** [comment]
Ping?
