### ISSUE TITLE
AES CBC padding not removed before dumping to TS file

### ISSUE THREAD

**Issue by e2iplayer** [selsta/hlsdl#40]
Hello,

Segments encrypted with AES CBC mode (AES-128) are padded before encryption. 
This padding should be removed after decryption. At now padding is dumped to the output file and this couse manny errors during processing TS.

How to reproduce the problem:
1. Download encrypted in AES-128 mode test stream: https://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8 
2. Analize downloaded output file with TS analizer for example with free DVBinspector-1.10.1

Expected result:
The should not be any parsing errors like: "Did not find sync byte, resyncing"

Current result:
There is manny parsing error because in the output file there are trash

**Comment by selsta** [comment]
I rebased to your latest version. Thanks again.
