### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pysj79** [selsta/hlsdl#5]
Hello, 

Im trying to download a SAMPLE-AES encrypted video, http://tv2-stream-od.online.no/vod2/_definst_/amlst:1007470_ps60000_pd1348980_HRDNGR.smil/playlist.m3u8

Then I get "Segmentation fault" after a split second. No more information when running with --verbose. 

When running a gdb-session I get the following output:
(gdb) run "http://tv2-stream-od.online.no/vod2/_definst_/amlst:1007470_ps60000_pd1348980_HRDNGR.smil/chunklist_b3253000.m3u8"
Starting program: /usr/local/bin/hlsdl "http://tv2-stream-od.online.no/vod2/_definst_/amlst:1007470_ps60000_pd1348980_HRDNGR.smil/chunklist_b3253000.m3u8"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0406700 (LWP 20842)]
[Thread 0x7ffff0406700 (LWP 20842) exited]
[New Thread 0x7ffff0406700 (LWP 20843)]
[Thread 0x7ffff0406700 (LWP 20843) exited]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.

Any clues?

**Comment by pysj79** [comment]
Forgot to put the backtrack-log from gdb:
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x000000000040353a in extend_url (url=0x7fffffffe3a8, baseurl=0x63f9c0 "http://tv2-stream-od.online.no/vod2/_definst_/amlst:1007470_ps60000_pd1348980_HRDNGR.smil/chunklist_b3253000.m3u8") at src/hls.c:30
#2  0x00000000004038ba in parse_playlist_tag (me=0x7fffffffe4c0, tag=0x656ce3 "#EXT-X-KEY:METHOD=SAMPLE-AES,URI=\"skd://stage-sumo.tv2.no/license/fairplay/1007470\",IV=0x", '1' <repeats 32 times>, ",KEYFORMAT=\"com.apple.streamingkeydelivery\",KEYFORMATVERSIONS=\"1\"\n#EXTINF:10.0,"...) at src/hls.c:98
#3  0x31223d534e4f4953 in ?? ()
#4  0x0000007700000022 in ?? ()
#5  0x00007fffffffe4c0 in ?? ()
#6  0x000000000000007c in ?? ()
#7  0x000000000000000a in ?? ()
#8  0x0000000000656c80 in ?? ()
#9  0x00007ffff62a2620 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000001950 in ?? ()
#11 0x0000000000401720 in fwrite@plt ()
#12 0x000000000063fd30 in ?? ()
#13 0x0000000000000000 in ?? ()

**Comment by selsta** [comment]
Hi,

The linked url above is protected using FairPlay DRM.
My tool can only download encrypted files that are not DRM protected.
