### ISSUE TITLE
Windows Binary

### ISSUE THREAD

**Issue by kumaranjeya** [selsta/hlsdl#52]
I tried compiling using "Cygwin" as suggested by SalamanderSandwich@ #31 . But, getting following error:
$ make
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -DPREFIX='"/usr/local"' -c src/hls.c -o src/hls.o
src/hls.c:11:10: fatal error: sys/prctl.h: No such file or directory
 #include <sys/prctl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:47: src/hls.o] Error 1

So, any suggestion or help on this please. Thank you and regards.

**Comment by selsta** [comment]
Please try again, I pushed https://github.com/selsta/hlsdl/commit/64b86df036d1ad1d30f6ebff26d311489611c3ac to master which might fix the problem.

**Comment by kumaranjeya** [comment]
Hi, Thank you for the quick response and reply. But now, getting following error:

$ make
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -DPREFIX='"/usr/local"' -c src/main.c -o src/main.o
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -DPREFIX='"/usr/local"' -c src/aes_openssl.c -o src/aes_openssl.o
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -DPREFIX='"/usr/local"' -c src/curl.c -o src/curl.o
src/curl.c: In function ‘get_data_from_localfile’:
src/curl.c:179:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (fread(*out, 1, readsize, fp) != readsize) {
                                          ^~
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -DPREFIX='"/usr/local"' -c src/hls.c -o src/hls.o
src/hls.c:106:5: warning: no previous prototype for ‘is_playlist_FPS’ [-Wmissing-prototypes]
 int is_playlist_FPS(char* source)
     ^~~~~~~~~~~~~~~
src/hls.c: In function ‘is_playlist_FPS’:
src/hls.c:108:12: warning: return makes integer from pointer without a cast [-Wint-conversion]
     return strstr(source, "KEYFORMAT=\"com.apple.streamingkeydelivery\"");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/hls.c: In function ‘last_strstr’:
src/hls.c:150:16: warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
         return (char*)haystack;
                ^
src/hls.c: In function ‘sample_aes_decrypt_audio_data’:
src/hls.c:893:27: warning: to be safe all intermediate pointers in cast from ‘uint8_t ** {aka unsigned char **}’ to ‘const uint8_t ** {aka const unsigned char **}’ must be ‘const’ qualified [-Wcast-qual]
     while (get_next_frame((const uint8_t **)&audio_frame, end_ptr, &frame_length)) {
                           ^
src/hls.c: In function ‘hls_playlist_update_thread’:
src/hls.c:1161:5: warning: implicit declaration of function ‘prctl’ [-Wimplicit-function-declaration]
     prctl(PR_SET_NAME, (unsigned long)&threadname);
     ^~~~~
src/hls.c:1161:11: error: ‘PR_SET_NAME’ undeclared (first use in this function)
     prctl(PR_SET_NAME, (unsigned long)&threadname);
           ^~~~~~~~~~~
src/hls.c:1161:11: note: each undeclared identifier is reported only once for each function it appears in
make: *** [makefile:47: src/hls.o] Error 1

Kindly help. Thank you and regards.

**Comment by selsta** [comment]
Please try again with latest master. Might still need a few more fixes.

**Comment by kumaranjeya** [comment]
I'm able to compile and able to download. But,
In linux, i'm can do "./hlsdl -v "https://www.taikr.com/hls/13929/playlist/sZY6cmGCdLAzhYZny1TLxsoCGWGIaHvF.m3u8" -o "1.ts"

In windows, only able to download with:
"hlsdl -v "https://www.taikr.com/hls/13929/playlist/PBQdcUl5ymlXRojht9nhKZkQJJ7qNcEj.m3u8"" with downloaded filename as "000_hls_output.ts"

I tried with "-o" but can't. What could be the issue?

Thank you for your time. Regards.

**Comment by kumaranjeya** [comment]
Hi, It's seems can do the following in Windows and it works,

hlsdl -v -o "1.ts" "https://www.taikr.com/hls/13929/playlist/gTzvH2ifRcha6LE8qS5AIDDg6yezGKQV.m3u8"

Meaning windows strictly following your preset usage rules:
**Usage: hlsdl [options] url**

 I would say this issue is settled. Thank you for your time. Appreciate it. Regards.

**Comment by selsta** [comment]
Good to hear.
