### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by liuhui19994** [selsta/hlsdl#54]
01:  ./hlsdl https://theater.kktv.com.tw/70/03000170010002_56a74815777321af3e492de24f555238/15033908132d5444cd08_hls.m3u8
1: Bandwidth: 4020000, Resolution: 1920x1080, Codecs: unknown
2: Bandwidth: 2181600, Resolution: 1280x720, Codecs: unknown
3: Bandwidth: 1371600, Resolution: 852x480, Codecs: unknown
4: Bandwidth: 805200, Resolution: 640x360, Codecs: unknown
5: Bandwidth: 559200, Resolution: 640x360, Codecs: unknown
6: Bandwidth: 374400, Resolution: 426x240, Codecs: unknown
Which Quality should be downloaded? 1
> START media_playlist_get_links
> END media_playlist_get_links
HLS Stream is SAMPLE-AES encrypted.
File already exists. Overwrite? (y/n) y
{"d_t":"vod"}
{"t_d":3951,"d_d":0, "d_s":0}
Downloading part 0
Error: Getting key-file [https://theater.kktv.com.tw/70/03000170010002_56a74815777321af3e492de24f555238/15033908132d5444cd08_hls/1080p_3192k.m3u8/../skd://8be594463ff19eda4a0f1fb53aa5a0a9+1196e36ba6d73c3ef1c21d2803235ae3] failed http_code[403].
{"t_d":3951,"d_d":5,"d_s":2271416}
Downloading part 1
Error: Getting key-file [https://theater.kktv.com.tw/70/03000170010002_56a74815777321af3e492de24f555238/15033908132d5444cd08_hls/1080p_3192k.m3u8/../skd://8be594463ff19eda4a0f1fb53aa5a0a9+1196e36ba6d73c3ef1c21d2803235ae3] failed http_code[403].
{"t_d":3951,"d_d":10,"d_s":4874652}
Downloading part 2

02:  $ ./hlsdl http://fppmdasia.foxplay.com/FoxPlus_Asia_DP/421/983/1024791107891-1540271615794-master.m3u8
1: Bandwidth: 3282000, Resolution: 1280x960, Codecs: avc1.4D4028,mp4a.40.2
2: Bandwidth: 2490000, Resolution: 1280x960, Codecs: avc1.4D4028,mp4a.40.2
3: Bandwidth: 828000, Resolution: 640x480, Codecs: avc1.42C01E,mp4a.40.2
4: Bandwidth: 399000, Resolution: 480x360, Codecs: avc1.42C01E,mp4a.40.2
5: Bandwidth: 1716000, Resolution: 960x720, Codecs: avc1.4D401F,mp4a.40.2
Which Quality should be downloaded? 1
1: Name: Mandarin, Language: cmn
2: Name: Cantonese, Language: yue
Which Language should be downloaded? 1
> START media_playlist_get_links
> END media_playlist_get_links
> START media_playlist_get_links
> END media_playlist_get_links
HLS Stream is SAMPLE-AES encrypted.
File already exists. Overwrite? (y/n) y
{"d_t":"vod"}
{"t_d":1120,"d_d":0, "d_s":0}
Downloading part 0
Error: Getting key-file [http://fppmdasia.foxplay.com/FoxPlus_Asia_DP/421/983/layer_4_x92e1e74422ad4bad99e731c296cacc64/MC10352262CT_x92e1e74422ad4bad99e731c296cacc64_4.m3u8/../skd://fairplay.entitlement.theplatform.com/fpls/web/FairPlay] failed http_code[404].
Downloading part 0
Error: Merged PMT to long for one TS packet!Error: Invalid context!
{"t_d":1120,"d_d":6,"d_s":0}
Downloading part 1
Error: Getting key-file [http://fppmdasia.foxplay.com/FoxPlus_Asia_DP/421/983/layer_4_x92e1e74422ad4bad99e731c296cacc64/MC10352262CT_x92e1e74422ad4bad99e731c296cacc64_4.m3u8/../skd://fairplay.entitlement.theplatform.com/fpls/web/FairPlay] failed http_code[404].
Downloading part 1
03:
./hlsdl https://sg01-vod-cfd.tvbanywhere.com.sg/fpsvods3/_definst_/smil:ints3/tvboverseas-media/mytvsuper15/38538/3853765/mps_000002781643.smil/playlist.m3u8 
Error: https://sg01-vod-cfd.tvbanywhere.com.sg/fpsvods3/_definst_/smil:ints3/tvboverseas-media/mytvsuper15/38538/3853765/mps_000002781643.smil/playlist.m3u8 403 tries[3]
Error: https://sg01-vod-cfd.tvbanywhere.com.sg/fpsvods3/_definst_/smil:ints3/tvboverseas-media/mytvsuper15/38538/3853765/mps_000002781643.smil/playlist.m3u8 403 tries[2]
Error: https://sg01-vod-cfd.tvbanywhere.com.sg/fpsvods3/_definst_/smil:ints3/tvboverseas-media/mytvsuper15/38538/3853765/mps_000002781643.smil/playlist.m3u8 403 tries[1]
{"error_code":403, "error_msg":""}
Warning: Not a valid M3U8 file. Exiting.

04:
 http://hk4-edge11-1.edgeware.tvb.com/session/f3cf5d6a-eea9-11e9-b60b-005056b12cf7/5qqpe5/mpsdrmv/_definst_/smil:vipo/34/6321/632011/mps_000000789889.smil/playlist.m3u8?token=b9be00149ef381c463b15400b48dad8c_1571161328_1571161328
1: Bandwidth: 1404000, Resolution: unknown, Codecs: unknown
Which Quality should be downloaded? 1
1: Name: Cantonese, Language: Cantonese
Which Language should be downloaded? 1
> START media_playlist_get_links
> END media_playlist_get_links
> START media_playlist_get_links
> END media_playlist_get_links
HLS Stream is AES-128 encrypted.
File already exists. Overwrite? (y/n) y
{"d_t":"vod"}
{"t_d":1555,"d_d":0, "d_s":0}
Downloading part 0
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 1804624, out_size: 1804608
{"t_d":1555,"d_d":10,"d_s":1804608}
Downloading part 1
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 1712688, out_size: 1712672
{"t_d":1555,"d_d":20,"d_s":3517280}
Downloading part 2
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 1768336, out_size: 1768320
{"t_d":1555,"d_d":30,"d_s":5285600}

What should I do?

**Comment by selsta** [comment]
hlsdl does not support DRM.

**Comment by liuhui19994** [comment]
Hello God, I got this software. It can decrypt widevine, support Netflix and amazon_prime video, but I won't use it. Can you teach me how to use it? Or add decryption DRM to your hlsdl, if you have time, can you teach me how to use it? Configuration is a bit complicated. I won't use it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"selsta"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月15日(星期二) 上午6:38
收件人:&nbsp;"selsta/hlsdl"<hlsdl@noreply.github.com&gt;;
抄送:&nbsp;"舍我其谁"<377516079@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [selsta/hlsdl] Help (#54)




hlsdl does not support DRM.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Nap36.rar (119.72M, 2019年11月14日 10:29 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=066565355d59e69a1715e5231237504d015503540400555315515456041a56030d00480d5102574f0d57065600560101015c0702343e622c591556031a4503103858&t=exs_ftn_download&code=8ee547bb

**Comment by selsta** [comment]
> It can decrypt widevine, support Netflix and amazon_prime video, but I won't use it.

Hello, can you explain what software you are talking about?

**Comment by liuhui19994** [comment]
I can't use it, so please help me




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "selsta"<notifications@github.com&gt;; 
发送时间: 2019年10月16日(星期三) 凌晨4:43
收件人: "selsta/hlsdl"<hlsdl@noreply.github.com&gt;; 
抄送: "舍我其谁"<377516079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [selsta/hlsdl] Help (#54)



 
It can decrypt widevine, support Netflix and amazon_prime video, but I won't use it.
  
Hello, can you explain what software you are talking about?
