### ISSUE TITLE
getting key-file error

### ISSUE THREAD

**Issue by raincurrent** [selsta/hlsdl#62]
command:
`hlsdl -b https://./index.m3u8`

error:
`Error: Getting key-file .`

The m3u8 is for free content. Might need indian region ip for accessing.

**Comment by selsta** [comment]
I see DRM and SKD in the error message. hlsdl does not support DRMed media.

**Comment by raincurrent** [comment]
What is SKD?

**Comment by selsta** [comment]
It hints at DRM, see here: https://docs.vdms.com/video/Content/Security/Apple-FairPlay-DRM.htm

**Comment by raincurrent** [comment]
ok thx.
