### ISSUE TITLE
A Dockerfile

### ISSUE THREAD

**Issue by whaike** [selsta/hlsdl#65]
```
FROM ubuntu:16.04

MAINTAINER whaike
WORKDIR /opt

RUN apt-get update \
    && apt-get install -y wget make git gcc

RUN wget https://www.openssl.org/source/openssl-1.1.0k.tar.gz \
    && tar -zxvf openssl-1.1.0k.tar.gz && cd openssl-1.1.0k && ./config && make install

RUN wget https://curl.haxx.se/download/curl-7.67.0.tar.gz \
    && tar -zxvf curl-7.67.0.tar.gz && cd curl-7.67.0 && ./configure && make && make install \
    && export PATH=$PATH:/usr/local/curl/bin

COPY ./hlsdl /opt/hlsdl

RUN apt-get update \
    && apt-get install -y libcurl4-openssl-dev lrzsz vim \
    && apt-get remove libssl1.0.0 -y \
    && cd /opt/hlsdl \
    && make && make install && make clean

WORKDIR /opt/hlsdl/data
ENV LANG C.UTF-8
CMD ['/bin/bash']
```
build image

`docker build -t hlsdl:1.1 .`

start  docker

`docker run --name hlsdl -v $PWD:/opt/hlsdl/data -dit hlsdl:1.1 /bin/bash`

go in

`docker exec -it hlsdl /bin/sh`

download

`hlsdl -b 'https://edu.aliyun.com/hls/13662/playlist/903eTtbpW7LECy2mcz974puMEDvYeXTB.m3u8?courseId=1651' -o 30.ts -v`

download to Local directory
```
#If the directory is mounted, you do not need to download it. Of course, you can also use the sz command without mounting.
sz 30.ts
```
Note：
1、`hlsdl -b ` Download the highest resolution by default, if not, you need to manually select the resolution
2.  Thanks to the author for his selfless dedication

**Comment by selsta** [comment]
Hello, can you post this in English?

**Comment by whaike** [comment]
> Hello, can you post this in English?

You can ignore the note only use the code ! （话说外国人应该不用阿里云大学甚至是中文视频吧，我觉得没必要非要翻译成英文，这反而会给国内部分同志带来困扰，如果您还是觉得有问题，请给出理由或删了此页）

**Comment by whaike** [comment]
> Hello, can you post this in English?

You can ignore the note only use the code ! （话说外国人应该不用阿里云大学甚至是中文视频吧，我觉得没必要非要翻译成英文，这反而会给国内部分同志带来困扰）

**Comment by alexhk** [comment]
Thanks for posting this, very helpful even it's been here for ages ;)

Adding some missing bits if somebody else comes along:

Save @whaike's file from above in your home directory with the name `Dockerfile`.

Now clone hlsdl to your home directory:

`git clone https://github.com/selsta/hlsdl.git -b master`

Then basically do what @whaike said...

build image

`docker build -t hlsdl:1.1 .`

start docker

`docker run --name hlsdl -v $PWD:/opt/hlsdl/data -dit hlsdl:1.1 /bin/bash`

go in

`docker exec -it hlsdl /bin/sh`

download

`hlsdl -b 'https://edu.aliyun.com/hls/13662/playlist/903eTtbpW7LECy2mcz974puMEDvYeXTB.m3u8?courseId=1651' -o 30.ts -v`

download to Local directory
