### ISSUE TITLE
Any chance to make a module or patch for a ffmpeg out of it?

### ISSUE THREAD

**Issue by fitz123** [selsta/hlsdl#7]

**Comment by selsta** [comment]
I’ve tried but failed :/

**Comment by sopparus** [comment]
can I input a hls key some how?

**Comment by selsta** [comment]
No, why would you need this feature?

**Comment by kaka052003** [comment]
i got this error in compile 


:~/hlsdl# make
cc src/main.o src/aes.o src/curl.o src/hls.o src/misc.o src/msg.o -lcurl -lavformat -lavutil -lavcodec -o hlsdl
src/hls.o: In function `decrypt_sample_aes':
/root/hlsdl/src/hls.c:478: undefined reference to `av_packet_unref'
collect2: error: ld returned 1 exit status


need help please
