### ISSUE TITLE
Didn't compile on Fedora 32 

### ISSUE THREAD

**Issue by charlesnl** [selsta/hlsdl#77]
Kept getting issues with compiling on Fedora 32

/usr/bin/ld: src/curl.o:(.bss+0x0): multiple definition of `hls_args'; src/main.o:(.bss+0x0): first defined here
/usr/bin/ld: src/hls.o:(.bss+0x0): multiple definition of `hls_args'; src/main.o:(.bss+0x0): first defined here
/usr/bin/ld: src/misc.o:(.bss+0x0): multiple definition of `hls_args'; src/main.o:(.bss+0x0): first defined here
/usr/bin/ld: src/msg.o:(.bss+0x0): multiple definition of `hls_args'; src/main.o:(.bss+0x0): first defined here
/usr/bin/ld: src/mpegts.o:(.bss+0x0): multiple definition of `hls_args'; src/main.o:(.bss+0x0): first defined here

solution was to add:

-z muldefs 
to the LDFLAGS in makefile, after adding that it compiles fine.

Just dropping it here, if someone else might run into it :)

**Comment by selsta** [comment]
Thank you, should be fixed in c14b0c9
