### ISSUE TITLE
how about a release for win7*64

### ISSUE THREAD

**Issue by MeMadMan** [selsta/hlsdl#8]
thanks

**Comment by selsta** [comment]
yea, i’ve tried it some time ago but failed. building stuff for windows is complicated.. sorry

**Comment by Dawks** [comment]
Hi selsta, on what platforms hlsdl works?

**Comment by Dawks** [comment]
Thanks for the reply, sorry but i'm new to this, what do i need to run it on Windows properly?

**Comment by selsta** [comment]
I’m not sure how to compile on Windows. Maybe try something like [msys2](http://www.msys2.org)

**Comment by Dawks** [comment]
Tried to compile it with TDM-GCC, or execute it with Dev-C++ and it fails with `[Error] libavformat/avformat.h: No such file or directory` even though ffmpeg is installed..

Will it work properly with MacOS? sorry to bother again but i really need this to work

**Comment by selsta** [comment]
I use macOS and it works fine. It works on Windows too if you install ffmpeg with the development libraries.
