### ISSUE TITLE
...

### ISSUE THREAD

**Issue by zackmark29** [selsta/hlsdl#84]
@selsta  could you tell me how I can view the progress of downloading?
I want to parse the download progress for my GUI version.
Thank you.

**Comment by selsta** [comment]
AFAIK there is currently no proper progress bar. I don’t think parsing hlsdl will be work perfect.

**Comment by zackmark29** [comment]
> AFAIK there is currently no proper progress bar. I don’t think parsing hlsdl will be work perfect.

I mean not progressbar, just the progress string. 
I want actually to match regex for the progress so that I can put it on my label

**Comment by selsta** [comment]
You can regex the `Downloading part 5` part.

**Comment by zackmark29** [comment]
> You can regex the `Downloading part 5` part.

Yeah that's what I did already. I thought there is command to get the progress percent (like 50% of 100%)
