### ISSUE TITLE
Error: Video or Audio missing.Segmentation fault: 11

### ISSUE THREAD

**Issue by soofuzz** [selsta/hlsdl#9]
Debug: Loglevel: 2
Choosing best quality. (Bitrate: 5605000)
HLS Stream is SAMPLE-AES encrypted.
Media Playlist parsed successfully.
Downloading 411 segments.
Downloading part 0
Error: Video or Audio missing.Segmentation fault: 11

thats the output im getting. does this mean the .ts is also protected hence it cant read what the put into the single .ts

**Comment by selsta** [comment]
Sample Link?

**Comment by rahulmg** [comment]
I'm getting the same issue
Link: https://cdn.cloud.altbalaji.com/content/2017-05/3063-5911c379f3d82/manifest.m3u8

hlsdl -b https://cdn.cloud.altbalaji.com/content/2017-05/3063-5911c379f3d82/manifest.m3u8
Choosing best quality. (Bitrate: 9237000)
HLS Stream is SAMPLE-AES encrypted.
Media Playlist parsed successfully.
Downloading 109 segments.
File already exists. Overwrite? (y/n) y
Downloading part 0
Error: Video or Audio missing.Segmentation fault (core dumped)

**Comment by selsta** [comment]
```
URI="skd://fairplay"
```

DRM, no way to download such files.

**Comment by rahulmg** [comment]
Thanks for the quick response
